name = "" # todo

main = "index.js"
compatibility_date = "2024-09-07"
send_metrics = false

[vars]
# 配置全局加密变量 需要再控制面板中设置全局变量，再此文件设置为明文全局变量
P6DD = "gateway.cf.shdrr.org"
P4DD = "gateway.cf.shdrr.org"
MMDD = "gateway.cf.shdrr.org"

# CF如果做二次域名跳转的话，请将VDST参数设置成二次域名
VDST = "togogg.shdrr.org"

# CF规则生成器的验证密码
WTPD
