name = "cloudgatekeeper"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [
    "nodejs_compat"
]


# 本地调试配置
[env.dev]
name = "cloudgatekeeper-dev"
port = 8787
local_protocol = "http"
ip = "localhost"
upstream_protocol = "https"
[env.dev.vars]
P6DD = "gateway.cf.shdrr.org"
P4DD = "gateway.cf.shdrr.org"
MMDD = "gateway.cf.shdrr.org"
VDST = "togogg.shdrr.org"
WTPD = "cloudgatekeeper"
# 生产环境构建配置
[env.dev.build]
command = ""


# 构建配置
[build]
command = ""
watch_dir = "src"
minify = true
node_compat = true

# 生产环境配置
[env.production]
name = "cloudgatekeeper-prod"

# 环境变量
[env.production.vars]
P6DD = "gateway.cf.shdrr.org"
P4DD = "gateway.cf.shdrr.org"
MMDD = "gateway.cf.shdrr.org"
VDST = "togogg.shdrr.org"
WTPD = "cloudgatekeeper"

# 生产环境构建配置
[env.production.build]
command = ""


